import{a as q,S as P,i as s}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const B="https://pixabay.com/api/",M="55703033-0c3414e280352f7ac0065df9c";async function f(r,t){return(await q.get(B,{params:{key:M,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".load-more"),p=document.querySelector(".loader"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:i,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>

        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${v}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){h.innerHTML=""}function y(){p.classList.add("is-visible")}function b(){p.classList.remove("is-visible")}function L(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}const u=document.querySelector(".form"),O=document.querySelector(".load-more");let n=1,l="",d=0;u.addEventListener("submit",async r=>{if(r.preventDefault(),l=u.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search query!",position:"topRight"});return}n=1,$(),w(),y();try{const t=await f(l,n);if(d=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),d>15?L():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({message:"Something went wrong!",position:"topRight"})}finally{b(),u.reset()}});O.addEventListener("click",async()=>{n+=1,w(),y();try{const r=await f(l,n);g(r.hits),x();const t=Math.ceil(d/15);n>=t?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch{s.error({message:"Something went wrong!",position:"topRight"})}finally{b()}});function x(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
